version: '3'
services:
  bakery-app:
    image: bakery-app:latest
    ports:
      # the bakery app
      - 9999:8080
      # jmx  
      - 5000:5000
      # jmx agent
      - 8888:8888
    volumes:
      - ./jmx:/tmp
    environment:
      - JAVA_TOOL_OPTIONS=-Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.port=5000 -Dcom.sun.management.jmxremote.rmi.port=5000 -Dcom.sun.management.jmxremote.host=0.0.0.0 -Djava.rmi.server.hostname=0.0.0.0 -javaagent:/tmp/jmx_prometheus_javaagent-0.17.2.jar=8888:/tmp/jmx-exporter.yaml
