apiVersion: apps/v1
kind: Deployment
metadata:
  name: bakery-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      run: bakery
  template:
    metadata:
      labels:
        run: bakery
    spec:
      containers:
        - name: bakery-app
          image: bakery-app:local
          imagePullPolicy: Never
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8889
            protocol: TCP
          env:
          - name: JAVA_TOOL_OPTIONS
            value: "-Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.port=5000 -Dcom.sun.management.jmxremote.rmi.port=5000 -Dcom.sun.management.jmxremote.host=0.0.0.0 -Djava.rmi.server.hostname=0.0.0.0 -javaagent:/opt/jmx/jmx_prometheus_javaagent-0.17.2.jar=8889:/opt/jmx/jmx-exporter.yaml"
---
apiVersion: v1
kind: Service
metadata:
  name: bakery-service
spec:
  type: NodePort
  selector:
    run: bakery
  ports:
    - nodePort: 30889
      name: jmx
      port: 8889
      targetPort: 8889
    - nodePort: 30880
      name: http
      port: 9998
      targetPort: 8080 
