---
- hosts: all
  become: yes
  remote_user: vagrant
  tasks:
  - name: deploy bakery-app
    community.docker.docker_container:
      image: bakery-app:latest
      name: bakery-app
      state: started
      auto_remove: true
      ports:
          # the bakery app
        - "9999:8080"
          # jmx
        - "5000:5000"
          # prometheus jmx javaagent
        - "8888:8888"
      volumes:
        - /opt/jmx:/tmp
      env: 
        JAVA_TOOL_OPTIONS: -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.port=5000 -Dcom.sun.management.jmxremote.rmi.port=5000 -Dcom.sun.management.jmxremote.host=0.0.0.0 -Djava.rmi.server.hostname=0.0.0.0 -javaagent:/tmp/jmx_prometheus_javaagent-0.17.2.jar=8888:/tmp/jmx-exporter.yaml
